name: angular_ui
version: 0.4.0
authors:
- Sergey Akopkokhyants <akserg@gmail.com>
- Tonis Pool <tonis.pool@gmail.com>
- Gunter Zochbauer <gzoechi@gmail.com>
- Francesco Cina <ufoscout@gmail.com>
description: Port of Angular-UI to Dart.
homepage: http://akserg.github.io/angular.dart.ui
environment:
  sdk: '>=1.3.0 <2.0.0'
dependencies:
  angular: '>=0.10.0 <0.11.0'
  js: '>=0.2.2 <0.3.0'
dev_dependencies:
  ghpages_generator: '>=0.1.0 <1.0.0'
  mock: '>=0.10.0+1 <0.11.0'
  unittest: '>=0.10.1+2 <0.11.0'
