name: angular_ui
version: 0.2.0
author: Sergey Akopkokhyants <akserg@gmail.com>, Tonis Pool <tonis.pool@gmail.com>.
description: Port of Angular-UI to Dart.
homepage: http://akserg.github.io/angular.dart.ui
environment:
  sdk: '>=1.0.0+10 <2.0.0'
dependencies:
  angular: #'>=0.9.4'
    git: git@github.com:angular/angular.dart.git
  browser: '>=0.9.1'
  js: '>=0.2.1'
  logging: '>=0.9.1+1'
  logging_handlers: '>=0.8.0'
dev_dependencies:
  unittest: '>=0.9.3'
