name: angular_ui
version: 0.2.0+7
authors:
- Sergey Akopkokhyants <akserg@gmail.com>
- Tonis Pool <tonis.pool@gmail.com>
- Gunter Zochbauer <gzoechi@gmail.com>
- Francesco Cina <ufoscout@gmail.com>
description: Port of Angular-UI to Dart.
homepage: http://akserg.github.io/angular.dart.ui
environment:
  sdk: '>=1.2.0 <2.0.0'
dependencies:
  angular: '>=0.9.8'
  logging_handlers: '>=0.8.0'
dev_dependencies:
  unittest: '>=0.10.0'
