name: angular_ui
varsion: 0.1.0
author: Sergey Akopkokhyants <akserg@gmail.com>
description: Angular-UI to Dart.
environment:
  sdk: '>=1.0.0+10 <2.0.0'
dependencies:
  angular: any
  browser: any
  js: any
dev_dependencies:
  unittest: any
